# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
lune = "lune-org/lune@0.10.1"
selene = "Kampfkarren/selene@0.29.0"
StyLua = "JohnnyMorganz/StyLua@2.1.0"

[tasks]
format = "bin/stylua src"
lint = "bin/selene src"